function [ddq1,ddq2,ddq3,ddq4] = autoGen_dynamics(x_CoM,z_CoM,theta,r_swFoot,dx_CoM,dz_CoM,dtheta,dr_swFoot,m_swLeg,m_swFoot,I_swLeg,I_swFoot,L_thigh,k_swFoot,k_swLeg,theta0,r_swFoot0,gravi,m_CoM,k0,L0,foot)
%AUTOGEN_DYNAMICS
%    [DDQ1,DDQ2,DDQ3,DDQ4] = AUTOGEN_DYNAMICS(X_COM,Z_COM,THETA,R_SWFOOT,DX_COM,DZ_COM,DTHETA,DR_SWFOOT,M_SWLEG,M_SWFOOT,I_SWLEG,I_SWFOOT,L_THIGH,K_SWFOOT,K_SWLEG,THETA0,R_SWFOOT0,GRAVI,M_COM,K0,L0,FOOT)

%    This function was generated by the Symbolic Math Toolbox version 8.1.
%    18-Jul-2019 11:58:08

t2 = cos(theta);
t3 = dtheta.^2;
t4 = sin(theta);
t5 = theta.*2.0;
t6 = sin(t5);
t7 = r_swFoot.^2;
t8 = L_thigh.^2;
t9 = m_CoM+m_swLeg;
t10 = 1.0./t9;
t11 = foot-x_CoM;
t12 = z_CoM.^2;
t13 = t11.^2;
t14 = t12+t13;
t15 = 1.0./sqrt(t14);
t16 = L_thigh.*m_swFoot.*t2.*t3;
t17 = m_swFoot.*r_swFoot.*t2.*t3;
t18 = I_swLeg.*m_CoM.*4.0;
t19 = I_swFoot.*m_CoM.*4.0;
t20 = I_swLeg.*m_swLeg.*4.0;
t21 = I_swLeg.*m_swFoot.*4.0;
t22 = I_swFoot.*m_swLeg.*4.0;
t23 = I_swFoot.*m_swFoot.*4.0;
t24 = m_CoM.*m_swFoot.*t7.*4.0;
t25 = m_swLeg.*m_swFoot.*t7.*4.0;
t26 = m_CoM.*m_swLeg.*t8;
t27 = m_CoM.*m_swFoot.*t8.*4.0;
t28 = m_swLeg.*m_swFoot.*t8;
t29 = L_thigh.*m_CoM.*m_swFoot.*r_swFoot.*8.0;
t30 = L_thigh.*m_swLeg.*m_swFoot.*r_swFoot.*4.0;
t31 = t18+t19+t20+t21+t22+t23+t24+t25+t26+t27+t28+t29+t30;
t32 = 1.0./t31;
t33 = t4.^2;
t34 = m_swLeg.^2;
t35 = m_CoM+m_swLeg+m_swFoot;
t36 = L0.*k0.*t15.*z_CoM;
t37 = L_thigh.*m_swLeg.*t3.*t4.*(1.0./2.0);
t38 = L_thigh.*m_swFoot.*t3.*t4;
t39 = m_swFoot.*r_swFoot.*t3.*t4;
t61 = k0.*z_CoM;
t62 = gravi.*t35;
t63 = dr_swFoot.*dtheta.*m_swFoot.*t2.*2.0;
t40 = t36+t37+t38+t39-t61-t62-t63;
t41 = t8.*t33.*t34;
t42 = m_swLeg.*m_swFoot.*t8.*t33.*3.0;
t43 = L_thigh.*m_swLeg.*m_swFoot.*r_swFoot.*t33.*4.0;
t44 = t8.*t34.*(1.0./2.0);
t45 = m_swLeg.*m_swFoot.*t8.*(3.0./2.0);
t46 = L_thigh.*m_swLeg.*m_swFoot.*r_swFoot.*2.0;
t47 = t44+t45+t46-I_swLeg.*m_swFoot.*2.0-I_swFoot.*m_swFoot.*2.0;
t48 = foot.*k0;
t49 = L0.*k0.*t15.*x_CoM;
t50 = dr_swFoot.*dtheta.*m_swFoot.*t4.*2.0;
t51 = L_thigh.*m_swLeg.*t2.*t3.*(1.0./2.0);
t59 = k0.*x_CoM;
t60 = L0.*foot.*k0.*t15;
t52 = t16+t17+t48+t49+t50+t51-t59-t60;
ddq1 = -t10.*(t16+t17+gravi.*m_swFoot.*t6.*(1.0./2.0)-k_swFoot.*r_swFoot.*t2+k_swFoot.*r_swFoot0.*t2)+t32.*(L_thigh.*m_swLeg.*(1.0./2.0)+L_thigh.*m_swFoot+m_swFoot.*r_swFoot).*(k_swLeg.*t4.*theta0.*4.0-k_swLeg.*t4.*theta.*4.0+gravi.*m_swFoot.*r_swFoot.*t6.*2.0+L_thigh.*gravi.*m_swLeg.*t6+L_thigh.*gravi.*m_swFoot.*t6.*2.0-L_thigh.*dr_swFoot.*dtheta.*m_swFoot.*t4.*8.0-dr_swFoot.*dtheta.*m_swFoot.*r_swFoot.*t4.*8.0)+t10.*t32.*t52.*(t18+t19+t20+t21+t22+t23+t24+t25+t26+t27+t28+t29+t30+t41+t42+t43-I_swLeg.*m_swFoot.*t33.*4.0-I_swFoot.*m_swFoot.*t33.*4.0)-t2.*t4.*t10.*t32.*t40.*t47.*2.0;
if nargout > 1
    t53 = foot.^2;
    t54 = x_CoM.^2;
    t57 = foot.*x_CoM.*2.0;
    t55 = t12+t53+t54-t57;
    t56 = sqrt(t55);
    t58 = m_swFoot.^2;
    t64 = k_swFoot.*r_swFoot0;
    t65 = m_swFoot.*r_swFoot.*t3;
    t66 = gravi.*m_swFoot.*t4;
    t67 = L_thigh.*m_swFoot.*t3;
    t68 = t64+t65+t66+t67-k_swFoot.*r_swFoot;
    ddq2 = -t4.*t10.*t68+t10.*t32.*t40.*(t18+t19+t20+t22+t24+t25+t26+t27+t29-t41-t42-t43+t8.*t34+I_swLeg.*m_swFoot.*t33.*4.0+I_swFoot.*m_swFoot.*t33.*4.0+m_swLeg.*m_swFoot.*t8.*4.0+L_thigh.*m_swLeg.*m_swFoot.*r_swFoot.*8.0)-t2.*t32.*(L_thigh.*m_swLeg+L_thigh.*m_swFoot.*2.0+m_swFoot.*r_swFoot.*2.0).*(k_swLeg.*theta0.*2.0-k_swLeg.*theta.*2.0-dr_swFoot.*dtheta.*m_swFoot.*r_swFoot.*4.0+gravi.*m_swFoot.*r_swFoot.*t2.*2.0-L_thigh.*dr_swFoot.*dtheta.*m_swFoot.*4.0+L_thigh.*gravi.*m_swLeg.*t2+L_thigh.*gravi.*m_swFoot.*t2.*2.0)-t2.*t4.*t10.*t32.*t47.*t52.*2.0;
end
if nargout > 2
    ddq3 = t15.*t32.*(k_swLeg.*m_CoM.*t56.*theta0.*2.0-k_swLeg.*m_CoM.*t56.*theta.*2.0+k_swLeg.*m_swLeg.*t56.*theta0.*2.0+k_swLeg.*m_swFoot.*t56.*theta0.*2.0-k_swLeg.*m_swLeg.*t56.*theta.*2.0-k_swLeg.*m_swFoot.*t56.*theta.*2.0+L_thigh.*gravi.*t2.*t34.*t56.*2.0+L_thigh.*gravi.*t2.*t56.*t58.*4.0+gravi.*r_swFoot.*t2.*t56.*t58.*4.0-k0.*m_swFoot.*r_swFoot.*t4.*t56.*x_CoM.*2.0+k0.*m_swFoot.*r_swFoot.*t2.*t56.*z_CoM.*2.0-L0.*L_thigh.*foot.*k0.*m_swLeg.*t4-L0.*L_thigh.*foot.*k0.*m_swFoot.*t4.*2.0+L0.*L_thigh.*k0.*m_swLeg.*t4.*x_CoM+L0.*L_thigh.*k0.*m_swFoot.*t4.*x_CoM.*2.0-L0.*L_thigh.*k0.*m_swLeg.*t2.*z_CoM-L0.*L_thigh.*k0.*m_swFoot.*t2.*z_CoM.*2.0-L_thigh.*dr_swFoot.*dtheta.*m_CoM.*m_swFoot.*t56.*4.0-L_thigh.*dr_swFoot.*dtheta.*m_swLeg.*m_swFoot.*t56.*2.0-L0.*foot.*k0.*m_swFoot.*r_swFoot.*t4.*2.0+L_thigh.*foot.*k0.*m_swLeg.*t4.*t56+L_thigh.*foot.*k0.*m_swFoot.*t4.*t56.*2.0+L_thigh.*gravi.*m_CoM.*m_swLeg.*t2.*t56.*2.0+L_thigh.*gravi.*m_CoM.*m_swFoot.*t2.*t56.*4.0+L_thigh.*gravi.*m_swLeg.*m_swFoot.*t2.*t56.*6.0+L0.*k0.*m_swFoot.*r_swFoot.*t4.*x_CoM.*2.0-L0.*k0.*m_swFoot.*r_swFoot.*t2.*z_CoM.*2.0-L_thigh.*k0.*m_swLeg.*t4.*t56.*x_CoM-L_thigh.*k0.*m_swFoot.*t4.*t56.*x_CoM.*2.0+L_thigh.*k0.*m_swLeg.*t2.*t56.*z_CoM+L_thigh.*k0.*m_swFoot.*t2.*t56.*z_CoM.*2.0-dr_swFoot.*dtheta.*m_CoM.*m_swFoot.*r_swFoot.*t56.*4.0-dr_swFoot.*dtheta.*m_swLeg.*m_swFoot.*r_swFoot.*t56.*4.0+foot.*k0.*m_swFoot.*r_swFoot.*t4.*t56.*2.0+gravi.*m_CoM.*m_swFoot.*r_swFoot.*t2.*t56.*4.0+gravi.*m_swLeg.*m_swFoot.*r_swFoot.*t2.*t56.*4.0).*2.0;
end
if nargout > 3
    ddq4 = -t4.*t10.*t40-t2.*t10.*t52+(t10.*t35.*t68)./m_swFoot;
end
